server:
  port: 7777

info:
  component: payments

logging:
  file: payments.log

hystrix:
  threadpool:
    default:
      coreSize: 350
      maximumSize: 350
      maxQueueSize: -1
      queueSizeRejectionThreshold: 20
      allowMaximumSizeToDivergeFromCoreSize: true

feign:
  hystrix:
    enabled: true

